#!/bin/bash
# Installation of map2model

git clone https://github.com/joferkington/mplstereonet.git
cd mplstereonet
python setup.py install

cd ../m2m_source
mkdir build
cd build
cmake ..
make
cp map2model ../../m2m_cpp/map2model

export DISPLAY=:99.0
which Xvfb
Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
sleep 3
exec "$@"