#!/bin/bash
# Installation of map2model

git clone https://github.com/joferkington/mplstereonet.git
cd mplstereonet
python setup.py install

cd ../m2m_source
mkdir build
cd build
cmake ..
make
cp map2model ../../m2m_cpp/map2model


rm -f /tmp/.X99-lock 
xvfb-run -s '-screen 0 1600x1200x16' \$@ >> /usr/local/bin/xvfbrun.sh
chmod +x /usr/local/bin/xvfbrun.sh
/usr/local/bin/xvfbrun.sh
